#[Site Info]
site_name: Gansche's TechStack
site_url: https://Gansche.github.io
site_author: Zhiuyuan Fang

#[Repository Info]
repo_name: Gansche.github.io
repo_url: https://github.com/Gansche/Gansche.github.io.git

#[Copyright]
copyright: Copyright &copy; 2024 Gansche

#[UI]
theme: 
  name: material
  logo: icon.png
  favicon: icon.png
  language: en
  direction: ltr

  palette: 
    - scheme: default
      primary: white
      accent: deep orange
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  # custom_dir: overrides

#[Extra]
extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Gansche
      name: Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:<zhiyuanfang413@gmail.com>
      name: E-Mail
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            <a href="https://github.com/Gansche/Gansche.github.io" target="_blank" rel="noopener">👉 Maybe a star?</a>
  
#[CSS]
#TODO:figure out how it works
extra_css:
  - css/basic.css
  # - css/admonition.css
  # - css/flink.css
  # - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.css

#[JavaScropt]
extra_javascript:
  - ""

#[Plugins]
plugins: 
  - search


#[Markdown Extensions]
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Content
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta

#[Navigation]
nav:
  - Home Page:
    - index.md
  - Knowledge:
    - knowledge/autoencoders.md